### ISSUE TITLE
Cycling

### ISSUE THREAD

**Issue by lukezona** [luckyshot/feathertest#1]
Hi, there is a way of using a for loop or a conditional statement (something like IF condition ? true : false )?

I tried using ft.step() but I have to put it in a if construct and I get a Syntax Error..

I'd like to fill 100 times the same form grabbing data from an array, so I have to load a page, fill the form with the first row of the array, submit, reload the first page and do it again for 100 times iterating the array..

There's a way to something like that?

**Comment by luckyshot** [comment]
Hi @lukezona,
You can now add a condition as a second parameter, if true it will jump:

``` javascript
ft.step( 123, a == b )
```

**Comment by lukezona** [comment]
Perfect, I still have a doubt: how can I increment a variable? I tried ft.set('counter', ft.get('counter') + 1) but it set 1 all the times...

**Comment by luckyshot** [comment]
As a temporary solution you can set it in the DOM somewhere, e.g.:

``` javascript
$('html').data( 'counter', 0 );
$('html').data( 'counter', $('html').data('counter') + 1 );

ft.step( 123, $('html').data('counter') < 100 )
```
